### PR TITLE
fix: remove replaceChildren

### PR DESCRIPTION
**Pull request by pearmini**
close: https://github.com/antvis/G2/issues/6363
close: https://github.com/ant-design/ant-design-charts/issues/2614

### CODE REVIEW

**Review by hustcc — APPROVED** [review]

**Review by lxfu1 — APPROVED** [review]

**Comment by wangxingkang** [comment]
CI 问题我本地已经解决 如何提给你？向 remove-replaceChildren 分支提 PR 吗

**Comment by wangxingkang** [comment]
image

**Comment by pearmini** [comment]
@wangxingkang 我先把这个 PR 合并了，你向 master 提就好啦。

**Comment by wangxingkang** [comment]
好的

**Comment by hustcc** [comment]
还需要发一个包～

**Pull request merged**
